### ISSUE TITLE
White Desktop background bug with Numix Frost and Frost Light themes

### ISSUE THREAD

**Issue by ItachiSan** [Antergos/Numix-Frost#14]
Hey,
I just installed the new version (**3.0**) of the theme on my **ArchLinux** (***Antergos***) and I have a weird white background on *Nautilus*.
![schermata da 2015-12-01 11-02-46](https://cloud.githubusercontent.com/assets/1223421/11497727/35fe575c-981b-11e5-8560-7916a8168ffb.png)
Killing Nautilus (with `nautilus -q`) fixes it:
![schermata da 2015-12-01 11-03-10](https://cloud.githubusercontent.com/assets/1223421/11497736/4c5a3bba-981b-11e5-9a46-595fc085070a.png)
Also, switching the *GTK* option in the **Tweak Tool** fixes it.

**Comment by 89luca89** [comment]
Seems a problem with the Nautilus background in desktop mode not being transparent (IIRC from nautilus 3.8, it does not draw the background but only a transparent view to show the wallpaper underneath)

Sadly I do not have much experience in GTK themes I don't know how to help debugging, but please let me know If I can do something to help!

**Comment by ItachiSan** [comment]
@89luca89 no idea to fix it here either.
I have no experience about **GNOME** themes.

Anyways, also opened a request upstream: shimmerproject#272

**Comment by momashi** [comment]
@lots0logs  do you keep a copy of the older versions of the numix frost light themes? If you send them to me, I could go through them and try to figure out at which of the version of the Theme this bug has appeared. I would then use diffuse (a differencing program for comparing the content of text files) to try and figure out what line is cause the bug, provided the changes between the bug free and bug introducing version don't range in the 1000s of lines... :)

**Comment by lots0logs** [comment]
@momashi Actually, I'm quite sure this bug showed up when the theme was completely rewritten in SCSS which, of course, makes it impossible to identify by comparing to previous versions :frowning:

**Comment by momashi** [comment]
@lots0logs  yeah that does complicate things quite a bit.... 

Do you mind if I have a copy of the pre-SCSS version of the Numix Frost Light theme?

**Comment by momashi** [comment]
@lots0logs Do you know which file in the theme  that is causing trouble? If you don't, I could try to narrow it down for you by downloading a SCSS based theme on gnome-look and see if there's white wallpaper issue. If there isn't, I'd start substituting files from Numix Frost into the working theme until I get the white desktop. That would probably give us at least the file that has the code that's causing the trouble. It could be a bug with their whole SCSS framework but I hope it's not...

**Comment by lots0logs** [comment]
@momashi Found an upstream bug report. Looks like its not the theme causing it: 

https://bugzilla.gnome.org/show_bug.cgi?id=747662

**Comment by momashi** [comment]
@lots0logs I think you might have sent me the wrong link because the problem described in the link doesn't mention background/wallpaper issue but nautilus crashing altogether.

**Comment by lots0logs** [comment]
Right but the reason the background is white is because Nautilus stops drawing the desktop (so it falls-back to GTK which simply shows the theme's base color).

**Comment by momashi** [comment]
ah, I see,

**Comment by momashi** [comment]
why do you think it happens with some themes and not others? You think's because some are written in SCSS and others are not?

**Comment by momashi** [comment]
Sorry, where would I go to check nautilus's logs. I can see if it has the same errors as the bugzilla, if it doesn't I'll open a new bug on their site.

**Comment by momashi** [comment]
@lots0logs could I have one of your old themes if it's still available? I could use while this bug is getting resolved.

**Comment by lots0logs** [comment]
The old version can be found on the [legacy](https://github.com/Antergos/Numix-Frost/tree/legacy) branch (or [legacy-light](https://github.com/Antergos/Numix-Frost/tree/legacy-light) for frost-light).

**Comment by momashi** [comment]
Thanks!

**Comment by axfelix** [comment]
FYI: https://github.com/shimmerproject/Numix/issues/272

**Comment by momashi** [comment]
I was still on GDM on my laptop. When I installed Antergos on my Desktop, I
was on lightDM, bug does not occur when in lightDM. It may be related to
GDM somehow.

**Comment by megax** [comment]
@lots0logs Fixed bug, removed paned code. https://github.com/numixproject/numix-gtk-theme/pull/482
Sample:
![image](https://cloud.githubusercontent.com/assets/461493/15991722/92a23e2c-30bb-11e6-8cfd-6eefa4f02d4b.png)

**Comment by megax** [comment]
@lots0logs Fixed issue: https://github.com/Antergos/Numix-Frost/commit/6064326cdac79aa0c4cac1ac0aaf13f73b03de94

**Comment by lots0logs** [comment]
@megax I thought I had already cherry-picked this from the main repo but I guess not :sweat_smile:

**Comment by ItachiSan** [comment]
@lots0logs when will this commit be present in the Antergos package?

**Comment by megax** [comment]
@ItachiSan Still having trouble? :)

**Comment by ItachiSan** [comment]
@megax nope, working flawlessly with last package :)

**Comment by megax** [comment]
Okay, please close issue :)
