### ISSUE TITLE
Cinnamon theme notification with large image thumbnail

### ISSUE THREAD

**Issue by bookletchoir** [Antergos/Numix-Frost#17]
On cinnamon, the notificaiton collapsed to text's height even with large image thumbnail.

What it looks like:
![numix-frost-themes](http://i.imgur.com/IE6gO6G.png)

What i expected (using numix theme)
![numix-themes](http://i.imgur.com/dE5KkZ1.png)

Can you do something with it?

**Comment by lots0logs** [comment]
Fixed in Antergos/numix-cinnamon@2b1f60c74a7f1a5d6ad00e8a1309f27197f1f903
