### ISSUE TITLE
cinnamon desktop theme is missing as of latest update

### ISSUE THREAD

**Issue by raidermax** [Antergos/Numix-Frost#18]
I was on version 2.5.4 or something similar and I very much liked the Cinnamon theme that was provided for Cinnamon. I have updated to the latest 3.0.4 and I very much dislike the new Cinnamon theme. Is there a way I can revert back just the Cinnamon.

Ive mitigated the issue by copying the cinnamon folder from /usr/share/themes/Numix-Frost-Light from a computer that did not update. It seems this update deleted the cinnamon folder from /usr/share/themes/Numix-Frost-Light ...not sure why, even if you are dropping support for cinnamon I still think you should just keep the folder included as many, like myself will use this theme for many years to come.

**Comment by lots0logs** [comment]
The Cinnamon Theme is a WIP. There are quite a few issues that will be addressed as soon as we find the time. There was never a light version of the Cinnamon theme. The theme was simply included in both  the light and dark versions of Numix-Frost. That resulted in having the same theme installed twice which is pointless and is why we don't include a copy in Numix-Frost-Light anymore. An alternative option is to install one of the 3rd-party versions of the theme that are available in the Cinnamon Theme repo.

Cheers!
