### ISSUE TITLE
weird scrollbars in some apps

### ISSUE THREAD

**Issue by fyvfy** [Antergos/Numix-Frost#20]
for example gnome-terminal http://snag.gy/6YSdK.jpg
cinnamon menu (can't printscreen it)

**Comment by abrowne** [comment]
I'm seeing the same thing in Gtk 3 apps when overlay scrollbars are disabled, either by the desktop environment (e.g. MATE) or because the app doesn't support it, such as Gtk 3 Firefox builds.
