### ISSUE TITLE
Support gnome-shell 3.20

### ISSUE THREAD

**Issue by dotsdl** [Antergos/Numix-Frost#25]
Tried giving the master branch a go on GNOME 3.20 under Arch, and it causes gnome-shell to crash. What's required to get the theme working for 3.20?

**Comment by lots0logs** [comment]
The gtk theme supports 3.20 (its beta quality at this stage). I was not aware that the shell theme was broken. Could you post the contents of your systemd journal after shell crashes?

**Comment by dotsdl** [comment]
Looks like the latest package from the Antergos repo works under 3.20. Thanks!
