### ISSUE TITLE
[GTK 3.20] volume/sound icon is black instead of light/white

### ISSUE THREAD

**Issue by Bednar87** [Antergos/Numix-Frost#26]
Hi there,

After upgrading to GTK 3.20 and Frost 3.2, the volume/sound icon turned dark in the tray. Screenshot attached.

http://imgur.com/bxO9q1M

EDIT: 3.4 hasn't fixed the issue

Thanks,

B

**Comment by lots0logs** [comment]
@Bednar87 Please let me know if this issue still occurs. Also just to confirm, which desktop are you using?

**Comment by Bednar87** [comment]
Hi,

Yes, it still occurs.

I am using XFCE. 

DE: XFCE4
WM: Xfwm4
WM Theme: Numix-Frost
GTK Theme: Numix-Frost [GTK2]
Icon Theme: Numix-Circle
Font: Roboto 10

Thanks!

**Comment by lots0logs** [comment]
There will be another update available in the next few hours. Please let me know if anything changes after installing the update and restarting your session. Thanks.

**Comment by Bednar87** [comment]
@lots0logs 

Updated to numix-frost-themes-3.5.r711 and the problem remains (as per the original screenshot)

B

**Comment by megax** [comment]
@Bednar87 @lots0logs Fixed bug: https://github.com/numixproject/numix-gtk-theme/pull/478

**Comment by Bednar87** [comment]
Thanks, do we know when it will hit the repos/AUR?
