### ISSUE TITLE
Shadows missing for headerbar windows (e.g. Nautilus)

### ISSUE THREAD

**Issue by dotsdl** [Antergos/Numix-Frost#28]
The shadows for windows with headerbars such as nautilus are either extremely light or don't exist at all.

![screenshot from 2016-04-10 12-22-55](https://cloud.githubusercontent.com/assets/1326811/14412421/586455ea-ff17-11e5-9723-a5a40515659d.png)

**Comment by lots0logs** [comment]
This was fixed in ab028997e8985db94871aedef8c2f35c782de92c and it's sibling commits
