### ISSUE TITLE
[GTK 3.20] libre office 5.X menu buttons are invisible

### ISSUE THREAD

**Issue by Bednar87** [Antergos/Numix-Frost#30]
Numix Frost 3.4

E: same on numix-frost-themes-3.5.r711

I am using XFCE. All packages updated to the latest versions.

DE: XFCE4
WM: Xfwm4
WM Theme: Numix-Frost
GTK Theme: Numix-Frost [GTK2]
Icon Theme: Numix-Circle
Font: Roboto 10

<a href="http://i.imgur.com/nXQLeDa.png">
  <img src="http://imgur.com/nXQLeDal.png" />
</a>

<a href="http://imgur.com/QQChcGH.png">
  <img src="http://imgur.com/QQChcGH.png" />
</a>

**Comment by ase1590** [comment]
also affected by this.

**Comment by Bednar87** [comment]
this is fixed now
