### ISSUE TITLE
Graphical gltiches when swtiching between applications

### ISSUE THREAD

**Issue by joelostblom** [Antergos/Numix-Frost#31]
I think the Numix frost Light and Dark are a couple of great themes with some really nice tweaks compared to the standard Numix theme, thanks for making it!

When I upgraded from Gnome 3.18 to 3.20, I started experiencing some strange graphical issues when changing focus from one application to another, either by alt-tab or clicking the new window with the mouse. So far, I have only seen this issue with gnome-apps (those that have the gnome-specific headerbar, such as Nautilus and gedit), and not with other apps (such as gnome-terminal and Firefox).

The glitches does only occur when using the Numix Frost GTK theme. A video of the behaviour can be [found here](https://vid.me/cCES) and I originally posted about this on [Unix StackExchange](http://unix.stackexchange.com/questions/276980/gnome-3-20-graphical-glitches-when-switching-applications), thinking it was a bug i Gnome 3.20.

**Comment by lots0logs** [comment]
Hi, this is an issue that is being tracked upstream here: https://github.com/numixproject/numix-gtk-theme/issues/362

**Comment by joelostblom** [comment]
Thanks for the link. Strangely, I only see this issue when using the Numix-Frost themes from the antergos repos, not the Numix theme from the community repos (v2.5.1.r154.9c9bf64-2).

**Comment by lots0logs** [comment]
The version in the community repo is not the latest master branch. I think if you try the latest master branch you will see the same issue.

**Comment by joelostblom** [comment]
According to the thread you linked, this was fixed a couple of days ago in https://github.com/numixproject/numix-gtk-theme/commit/6532bce86f356b5281027242ee8e3c8d9efc840c, although https://github.com/numixproject/numix-gtk-theme/commit/3cc526c0d6b1a59049b3d91ba490fb66b5281f1c?diff=unified is still open.

**Comment by lots0logs** [comment]
This was fixed in ab028997e8985db94871aedef8c2f35c782de92c & it's sibling commits.

**Comment by joelostblom** [comment]
Great, thank you!
I tried adding the changes from that commit manually on my machine hoping for a quick fix, but I couldn't get it to work so I guess it depends on a few of its parent commits. Looking forward for this to land in the antergos repo and thanks again for fixing it!
