### ISSUE TITLE
[GTK 3.20] lightdm-gtk-greeter is broken

### ISSUE THREAD

**Issue by jeweloper** [Antergos/Numix-Frost#33]
Since the update to GTK+ 3.20 the design of some controls on the lightdm-gtk-greeter is broken.
For example the top-panel is not transparent anymore and the background colour of user-combobox, password-input and login-button is white now.

It is caused by the introducing of css nodes with GTK 3.19. https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

**Comment by lots0logs** [comment]
@jeweloper Please see my notes on the PR. Thanks!! :smile:

**Comment by jeweloper** [comment]
@lots0logs I fixed it.
Additionally I add a left padding for the menubar. Nothing to do with this bug, only to optimize the appearance. ;)
