### ISSUE TITLE
[GTK 3.20] Firefox - Tooltips invisible

### ISSUE THREAD

**Issue by jeweloper** [Antergos/Numix-Frost#38]
Tooltips in Firefox 47.0 are invisible/unreadable, because of white tooltip-text on (nearly) white tooltip-background.

**Comment by megax** [comment]
Fixed numix: https://github.com/numixproject/numix-gtk-theme/commit/5257fb62fdfa0a731fa203dae78ebbe3988e0226 https://github.com/numixproject/numix-gtk-theme/commit/848411d0dd09f54e1828cd6b309158ea001b156a

**Comment by jeweloper** [comment]
You are right. Thanks for the hint.

**Comment by jeweloper** [comment]
Fixed in 3.5.r766.
