### ISSUE TITLE
Lower border/edge below panel is dead

### ISSUE THREAD

**Issue by amo13** [Antergos/Numix-Frost#40]
I noticed on my and on another freshly installed antergos with cinnamon this annoying little problem:
My Panel is at the lower border of the screen with the menu button to the left and with the workplace switcher at the right corner. When I move the mouse to the extreme lower left corner edge and click, I expect the menu button to be triggered and the menu to pop up, but nothing happens, as if the mouse just went one pixel to far behind the menu button, which should not be possible. The same happens at the lower right corner: When scrolling the mouse wheel, I expect to switch workplaces, but I need to move it back up (and at the right corner even a bit back to the left) again, to hover over the workplace switcher.
This is not a big deal, but still annoying, since I use these two things very frequently every day. 
After posting on the antergos [forum](https://forum.antergos.com/topic/4774/lower-border-edge-below-panel-is-dead), I found out, that it's the theme and lower corner clicks works just fine with the normal "cinnamon" theme, but I do prefer the numix frost theme.

**Comment by jeweloper** [comment]
The problem described by amo13 is caused by the panel-padding mentioned in issue #32.
