### ISSUE TITLE
Volume and clipman icons are black instead of light/white

### ISSUE THREAD

**Issue by Bednar87** [Antergos/Numix-Frost#42]
I previously reported this under [GTK 3.20] volume/sound icon is black instead of light/white #26

The issue has returned after the latest update. 

I am using XFCE. All packages updated to the latest versions.

DE: XFCE4
WM: Xfwm4
WM Theme: Numix-Frost
GTK Theme: Numix-Frost [GTK2]
Icon Theme: Numix-Circle
Font: Roboto 10

http://storage7.static.itmages.com/i/16/0921/s_1474478926_7894123_ab69ec5f7f.png

**Comment by WernerFP** [comment]
Workaround:

~/.config/gtk-3.0/gtk.css

[gtk.txt](https://github.com/Antergos/Numix-Frost/files/487605/gtk.txt)

**Comment by megax** [comment]
@Bednar87 Fixed: https://github.com/Antergos/Numix-Frost/commit/659fd9ae1e590cdf4fbc3109fb9eff62f8dc4e7b

**Comment by Bednar87** [comment]
Indeed. Closing. 

Thanks :)
