### ISSUE TITLE
Sidebars too bright in Numix Frost Light

### ISSUE THREAD

**Issue by cisoun** [Antergos/Numix-Frost#5]
Hi !

Since your first commit of may 16th, sidebars backgrounds are too bright.
Was it intented ?

Here's a screenshot to see what I mean. IMHO, the upper left version is better : 
![numixfrost](https://cloud.githubusercontent.com/assets/930282/7734733/6eed7772-ff38-11e4-888c-b3a5172ba87b.jpg)

Thanks for your work by the way.

**Comment by lots0logs** [comment]
addressed in 3.0 rewrite.
